services:
  xmrig-proxy:
    build:
      context: .
      dockerfile: Dockerfile.xmrig-proxy
    restart: unless-stopped
    environment:
      XMRIG_UPSTREAM_URL: ${XMRIG_UPSTREAM_URL}
      XMRIG_UPSTREAM_HASHVAULT_URL: ${XMRIG_UPSTREAM_HASHVAULT_URL}
      XMRIG_UPSTREAM_SUPPORTXMR_URL: ${XMRIG_UPSTREAM_SUPPORTXMR_URL}
      XMRIG_UPSTREAM_USER: ${XMRIG_UPSTREAM_USER}
      XMRIG_UPSTREAM_PASSWORD: ${XMRIG_UPSTREAM_PASSWORD}
      XMRIG_COIN: ${XMRIG_COIN}
      XMRIG_API_PORT: ${XMRIG_API_PORT}
      XMRIG_API_TOKEN: ${XMRIG_API_TOKEN}
    ports:
      - "${XMRIG_API_BIND}:${XMRIG_API_PORT}:${XMRIG_API_PORT}"
      - "${XMRIG_STRATUM_BIND}:${XMRIG_STRATUM_PORT}:3333"

  webui:
    build:
      context: .
      dockerfile: Dockerfile.webui
    restart: unless-stopped
    depends_on:
      - xmrig-proxy
    ports:
      - "${WEBUI_BIND}:${WEBUI_PORT}:80"
